[package]
name = "NayaCore"
version = "0.1.0"
edition = "2021"

[dependencies]
tungstenite="*"
serde = { version = "1.0.208", features = ["derive"] }
serde_json = "1.0.125"
colored="*"
chrono="*"

[lib]
name="Nayabot_Core"