[package]
name = "NayaBot"
version = "0.1.0"
edition = "2021"

[dependencies]
ws="*"
serde = { version = "1.0.208", features = ["derive"] }
serde_json = "1.0.125"
colored="*"
chrono="*"
lazy_static="*"
rusqlite="*"
serde_rusqlite="*"