[package]
name = "NayaCore"
version = "0.1.0"
edition = "2021"

[dependencies]
tungstenite="0.24"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
colored="2.1"
chrono="0.4.38"
futures="*"

[lib]
name="Nayabot_Core"