[package]
name = "nayabot_core"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
colored="2.1"
chrono="0.4.38"
anyhow="1.0.89"
reqwest={version="0.12",features = ["json"]}
tungstenite="0.24"

[lib]
name="nayabot_core"